name: nyamtam
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  firebase_core: ^2.25.3
  flutter:
    sdk: flutter
  #firebase_core: ^13.1.0
  #firebase_auth: ^13.1.0
  #google_sign_in: ^13.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
