// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQmAaBz0JqHLUDPHPvxFiEdk3FRI3q0As',
    appId: '1:525684710603:web:1944710189f2657422cf4e',
    messagingSenderId: '525684710603',
    projectId: 'nyamtam-d69a0',
    authDomain: 'nyamtam-d69a0.firebaseapp.com',
    storageBucket: 'nyamtam-d69a0.appspot.com',
    measurementId: 'G-VT56E0KWFL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLzZ6Cy5Fgrq5evomEOV-wZsTvsf1rjYE',
    appId: '1:525684710603:android:f154a56caa7ce68d22cf4e',
    messagingSenderId: '525684710603',
    projectId: 'nyamtam-d69a0',
    storageBucket: 'nyamtam-d69a0.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUJmjYlvn3yqHLdsUzFJGIbWKLvrKB0tg',
    appId: '1:525684710603:ios:97a65e5bb9523c5322cf4e',
    messagingSenderId: '525684710603',
    projectId: 'nyamtam-d69a0',
    storageBucket: 'nyamtam-d69a0.appspot.com',
    iosBundleId: 'com.example.nyamtam.RunnerTests',
  );
}
